Description: Creates an SNS topic with policy allowing codestar notification.

Parameters:
  TeamName:
    Type: String
    Description: Name of the Team
  ApplicationName:
    Type: String
    Description: Name of the Application
  KmsCmkARN:
    Type: String
    Description: Enter KMS-CMK key from <SourceAccount>
  NotificationEmail:
    Type: String
    Description: An email address for notification purposes.

Resources:
  SNSApprovalTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName:  !Sub ${TeamName}-${ApplicationName}-pipeline-notification
      TopicName: !Sub ${TeamName}-${ApplicationName}-pipeline-notification
      KmsMasterKeyId: !Ref KmsCmkARN

  SNSAccessPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Version: '2008-10-17'
        Id: SNS_for_codepipeline_policy
        Statement:
        - Sid: SNS_for_codepipeline_general_access
          Effect: Allow
          Principal:
            AWS: "*"
          Action:
          - SNS:GetTopicAttributes
          - SNS:SetTopicAttributes
          - SNS:AddPermission
          - SNS:RemovePermission
          - SNS:DeleteTopic
          - SNS:Subscribe
          - SNS:ListSubscriptionsByTopic
          - SNS:Publish
          - SNS:Receive
          Resource: !Ref SNSApprovalTopic
          Condition:
            StringEquals:
              AWS:SourceOwner: !Sub ${AWS::AccountId}
        - Sid: Allow_codestar_notification_publish
          Effect: Allow
          Principal:
            Service: codestar-notifications.amazonaws.com
          Action: SNS:Publish
          Resource: !Ref SNSApprovalTopic
          Condition:
            StringEquals:
              aws:SourceAccount: !Sub ${AWS::AccountId}
      Topics:
        - !Ref SNSApprovalTopic

  EmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref SNSApprovalTopic
      Endpoint: !Ref NotificationEmail
      Protocol: email

Outputs:
  SNSTopicArn:
    Description: ARN of the topic created.
    Value: !Ref SNSApprovalTopic
